apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: docker-registry-pod
    group: service
  name: docker-registry-pod
  namespace: reg
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: docker-registry-pod
  template:
    metadata:
      labels:
        app: docker-registry-pod
        group: service
    spec:
      containers:
      - image: registry:latest
        imagePullPolicy: Always
        name: registry
        ports:
        - containerPort: 5000
          name: 5000tcp02
          protocol: TCP
        resources:
          limits:
            cpu: "2"
        securityContext:
          capabilities: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/registry
          name: data-disk
        - mountPath: /etc/docker/registry/
          name: configvol
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 2000
        runAsGroup: 2000
        runAsUser: 200
      terminationGracePeriodSeconds: 30
      volumes:
      - name: data-disk
        persistentVolumeClaim:
          claimName: docker-repo-pvc
      - configMap:
          defaultMode: 256
          name: dockerconfig
          optional: true
        name: configvol